name: Android Kernel Build

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          git bc bison flex build-essential \
          zip curl zstd cpio libssl-dev \
          libelf-dev python3 clang lld llvm

      - name: Clone Proton Clang
        run: |
          git clone --depth=1 \
          https://github.com/kdrag0n/proton-clang.git clang

      - name: Export environment
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "SUBARCH=arm64" >> $GITHUB_ENV
          echo "PATH=$PWD/clang/bin:$PATH" >> $GITHUB_ENV

      - name: Configure kernel
  run: |
    make O=out ARCH=arm64 gki_defconfig
    ./scripts/config --file out/.config -d WERROR
    make O=out ARCH=arm64 olddefconfig
    
- name: Build kernel
  run: |
    make -j$(nproc --all) \
      O=out \
      ARCH=arm64

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: Kernel
          path: |
            out/arch/arm64/boot/Image*
            out/arch/arm64/boot/*.dtb
            out/arch/arm64/boot/dts/**/*.dtb
